apiVersion: v1
kind: Service
metadata:
  name: api-customer
spec:
  type: NodePort
  selector:
    app: api-customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
